language: python
python:
- '2.7'
addons:
  postgresql: '9.3'
services:
- postgresql
env:
  global:
  - DEBUG=True
  - USE_S3=1
  - AASHE_DRUPAL_URI=http://www.aashe.org/services/xmlrpc
  - AASHE_DRUPAL_KEY_DOMAIN=acupcc.aashe.org
  - AASHE_DRUPAL_COOKIE_DOMAIN=.aashe.org
  - DATABASE_URL=postgresql://postgres@localhost/travis_ci_test
  - SECRET_KEY=blahblahblah
  - AWS_STORAGE_BUCKET_NAME=aashe-conference-test
  - secure: zkNz0r4DcqZxWtlAGx7Ndw1t7AUQmVNYFPouGlZxHHzG3x1mwWAjafcgzH39plVm5fMsA9D34asZ82U8cnDCNYfJYvzXNt5rKpfTUb7IBLLbTHeK2N7piDu/CpsiNnBtGD+gcNNLttKgj9UjKy5hRLs+LVlt62spJ1wGISk7U761ysrXRr+gTc+HPVlpEsXnKXRSlRzgQT5OAf8D7LF4DXVPTxE+QFbnNryy4H8EYsw+HlqlO5PZCpgddoaMUwIUmyEYbonL9iY1k4GSfAM4lm09wKqHg+5GY6K/JbOkgTu7XyDGyurJhD+hfz9YVICwC6jQLettUYRp2mCWESIYn338JKp0IHwsGo6YtzywFkjM6Rpc0vS00McHAYgRakmzeW1QZxT/AWnhSe8IFC86ZlJUwZQ3vhMVa76Ol95SFmJOqehMJCF61ETIfdLKBkah+WnLmuJidU+KHf74yDq1nbunoX/lXiuP4VAM/v+ukHilfJJTVlKvEBz7WHNWGez+PlOcIH3iXVR/nrLBM5rxsatzVoafrOy4mTHK20g2wnd7U7/oXUIJ7cVEp+Uhc/dayu6dP6tK1aKY8YPRyfBLWfTtHqGkeqhJpuEVZxfS1z73cm5AF1uEXbf0rxWeRtEinqsdtXDVOxMLDBnpSXXGTijnfy0/J1clLAtepbpW1X8=
  - secure: Dt6urZUYDAUHVrI/zLkHj8qX1aXRCUojYdUFvX6al6sN9RFBOlQXQQBpl+Ho89RcCgLEMYsR7itxwGKfSpM8ni/SHVjqJxAH10JUsURzOdnP/TeSpFDfYF6F+VpQyFsDkLr34rJpbD759X1LDvUGPwU1Y8iPfEarubsYu2zRleIdw3oSBFkNKpsVFdyr2YKRDxWxr5CKVFFg/d9PJjbxSawUr0+AvQeT3gFKmuYZgZAjxiWK6GvGCNSBaqLwBo7ZyBJakniCGhIKb4wiwgaMa4voZw+hesjO/OavHX0K5CTXzNCCkkCJ31PzfLE8UfYPVXHPpZNtLySe1PiEPGfDPlUmF+C3AM84+oGYGQZassOZOd2Za7Ksa/wygBSzEv07S+pePlewNHM0qowidhFmPhTOnPSu8PPDm7n57oTm8nxgbIcKpaQYmeivAPHXtGnfIxdKpYY+T6KkvJgfgaWt4Ym2f5drG7JjqF+xqP4nbFgtgouomdVWK/RUVmfqdAyH9jdt9Tke8BHrS9jvpdysbQfWAUmsBHoqnNbImAB4eltHfnvMiB3ZD+yj9GqROGm2AY15ZI6jZVWGng9K7MBXAolJG/REcDYzbYA4MPIhYKUpAoCSzD5FS0CoGsRxPXsINaypT2m+rfz6fMkLYhInjmX6iV1xXWTDaRUwamma6UA=
  - secure: GqaiwGE4iKItFe1OlwJSpBhDuwV2f0zoa2iQk912mh2b1WlVQSmVlmoH3n98vYQBW+5UAuOTQNj0NuhuU8Ag5pAr6y4RUtOinnNhZYa8r3A5OIPVbxhVxaBNVXCbGXl8cm/729LVo8DDqpxa6oGvChmr24CLAkBmvjq6t0MFhWUnNsdZ5uhNFAj0tfQmTZ3mAeTw0ykzVxkwTmCVAy+nd6OTSlAx38j2s1/7RJI9nCQcWX+zpR7K1ab6NYoivOd6KLlzu4EvWz3L3g+4pnJc7cvtA8W9NCs6EPomL+tqL9VL8f+AJ6ZNJuXUWBmwF6vUZSkACQOyZECUFLk/HI/YlUTazp1DOp5XDWvtf0zl3gfwuYgKK2UWpL+42l9ARL7/0W/kwTzXAV30tg53JHP/zMziWXepgiWxQjHIt89l2TbbsLpJ10vLY+obqnWetbFOnUpIsXfED6VgwgP8qoem0SpGbKDTkwM3+9s6yW+niSckOtEFifHihFK7yFdVUKvkbudGporaudPPtCtypVkTh8WzP1GEyoPcElkOW69ziU+PTO72A0PGd8Wi+yQMx696+pNT2T8bGbwGjg1JobxzMyYsx7R5cB8xBdnuM9QgxkiSJPXFbMwweus9/Q2j7a2j1KvhozJt0Tn4Hdbxb1wV+Ias3qaplBZfhE2lu+Dzn7o=
  - secure: AaDd84bkaV3Rd9UBW35uSDQWSGEkyqyovHjVcAWdqg5696B/UInsLA3e9gWXDoO3RzNovF4lGY+11c8+tgoDVHo+1ulkDkXiBOgYdNOWc5LDE6IMdEByMMjeYm6KsSXA2uvsKSm/ZcfV3xn3NjSscWBLP+B1ajGgmNI7d7k1FE1+/VKGmSnMq5GVPdWe4v8j/4HP3GP4io4N/diLrx4Ha1zj4QZ8X69lxEu6WZA2p95/doHw+hGeWwR1zsq+FURJhHn9IhTia5sROV9sQIulHkU9n3RZHvTj5CqaSf86mDVqno4fvvMm3u0PT8BKgQ8eKn9oB+NNQARXK+EvGoU+r9sn3EKwwGhVDpusf9GO7hRGPzSoYX77lAE5i7Tz+r3lajsiyd/uMA9lTXZofrWTQpJ7wdndj491wOAQ7kFuWS506/xjTkr3IgcGIvZMb42EOliJMEC6UoDIpBa8ata90v4oqGIiN/wbXjwIsvS3ZZi3nFicCTr607HMsOwYQZVqm7v9bKyE8ugiRTwoH3Dh6z6vl9Bz+L8zIq1atjLK6HFDW/kCm78U3ae0hsxxWCk9Nqr81noFklyltSUpQzh4dxZYZQLCdfULKp/6cyZLb4MdkM6rAXFeSmJ7nTM7IsvdVrhN8uNhesTncCerlQYRrH5DAcO6SXPpDJBQSR6cHeY=
install:
- pip install setuptools>=18.5
- pip install -r requirements.txt
- pip install -r requirements_test.txt
script: coverage run manage.py test -v3
after_success: coveralls
notifications:
  hipchat: 5534a6204d6caa1a45ac2444282aca@WebDevActivity
  email: false
